### ISSUE TITLE
Error on a 2nd depositor withdrawal

### ISSUE THREAD

**Issue by Pongch** [bazaarfinance/bazaarfinance#15]
This test starts failing for an unknown reason. After the 2nd deposit and withdrawal by the depositor, solc throws an error `revert 5`. Stack trace shows a call to a lending pool contract. 

1) Vault Contract Smoke Test with depositor1, depositor2 and recipient:
       *T7 depositor1 deposits again and then withdraw:
     Error: VM Exception while processing transaction: revert 5
      at <UnrecognizedContract>.<unknown> (0x7d2768de32b0b80b7a3454c06bdac94a69ddc7a9)
      at <UnrecognizedContract>.<unknown> (0x7d2768de32b0b80b7a3454c06bdac94a69ddc7a9)
      at <UnrecognizedContract>.<unknown> (0x7d2768de32b0b80b7a3454c06bdac94a69ddc7a9)
      at Vault.withdraw (contracts/Vault.sol:158)
      at <UnrecognizedContract>.<unknown> (0xe451980132e65465d0a498c53f0b5227326dd73f)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1303:9)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18)
      at EthersProviderWrapper.send (node_modules/hardhat-deploy-ethers/src/ethers-provider-wrapper.ts:13:20)

**Comment by Pongch** [comment]
list of error types show that the error is 'User cannot withdraw more than the available balance'

https://github.com/aave/protocol-v2/blob/29448c19c1e9b8aa87dccd70b716d15cdf4128f6/helpers/types.ts
